# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

[package]
name = "agda-index"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
scraper = "0.14.0"
url = "2.3.1"
